-- Insert SQL Rules Here 

--Crop Quotas- Requires Freedom
--Industrial Plunder- Requires Order
--Living Space- Requires Autocracy
INSERT INTO Policies (Type, Level, PolicyBranchType, Description, Civiliopedia, Help, CultureCost)

VALUES ('POLICY_CROP_QUOTAS', 1, 'POLICY_BRANCH_FREEDOM', 'TXT_KEY_POLICY_CROP_QUOTAS','TXT_KEY_POLICY_CROP_QUOTAS_TEXT','TXT_KEY_POLICY_CROP_QUOTAS_HELP',10),

('POLICY_INDUSTRIAL_PLUNDER', 1, 'POLICY_BRANCH_ORDER', 'TXT_KEY_POLICY_INDUSTRIAL_PLUNDER','TXT_KEY_POLICY_INDUSTRIAL_PLUNDER_TEXT','TXT_KEY_POLICY_INDUSTRIAL_PLUNDER_HELP',10),

('POLICY_LIVING_SPACE', 1, 'POLICY_BRANCH_AUTOCRACY', 'TXT_KEY_POLICY_LIVING_SPACE','TXT_KEY_POLICY_LIVING_SPACE_TEXT','TXT_KEY_POLICY_LIVING_SPACE_HELP',10);

